title: Manoa Lost & Found
description: A UH MƒÅnoa community app to report, browse, and recover lost items.
theme: jekyll-theme-cayman

# Optional customization
show_downloads: false
google_analytics: false
include:
  - custom.css
